miniproject/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',view=views.home,name='home'),
    path('student/',include('student.urls')),
    path('teacher/',include('teacher.urls')),
]

student/urls.py
from django.contrib import admin
from django.urls import path
from . import views
app_name='student'
urlpatterns = [

    path('student_login',view=views.student_login,name='student_login'),
    path('student_register',view=views.student_register,name='student_register'),
    path('student_info/<int:id>/',view=views.student_info,name='student_info'),
]

teacher/urls.py
from django.contrib import admin
from django.urls import path
from . import views
app_name='teacher'
urlpatterns = [

    path('teacher_login',view=views.teacher_login,name='teacher_login'),
    path('teacher_dashboard/<int:id>/',view=views.teacher_dashboard,name='teacher_dashboard'),
    path('teacher_dashboard/notice',view=views.notice,name='notice'),
    path('teacher_dashboard/attend',view=views.attend,name='attend'),
    path('teacher_dashboard/marks',view=views.marks,name='marks'),
]

teacher/models.py
from django.db import models
from student.models import Staff
department_choice=['CN','CNS','DAA','SPOS','DAA']


class Teacher(models.Model):
    staff=models.OneToOneField(Staff,on_delete=models.CASCADE,related_name='teacher_profile')
    teacher_name=models.CharField(max_length=200)
    department=models.IntegerField(choices=((i,x) for i,x in enumerate(department_choice)),default=0)

    def __str__(self):
        return self.teacher_name
class Notice(models.Model):
    notice=models.CharField(max_length=500)
    date_published=models.DateField(auto_now=True)

    def __str__(self):
        return str(self.notice)

teacher/views.py
from django.shortcuts import render,redirect,render_to_response
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.template import RequestContext
from django.http import HttpResponseRedirect,HttpResponse
from .models import Notice,department_choice
from student.models import Staff,Student,Attendence,Marks
def notice(request):
    if request.POST:
        n = request.POST['notice']
        obj=Notice(notice=n)
        obj.save()

        return render(request,'teacher_dashboard.html')
    return render(request,'noticeform.html')


def attend(request):
    list_of_student_id=[]
    list_of_staff=Staff.objects.all()
    for staff in list_of_staff:
        if not staff.is_teacher:
            list_of_student_id.append(staff.id)
    if request.POST:
        student_id=request.POST['student_id']
        days_attended_s1=request.POST['days_attended_s1']
        total_attended_s1=request.POST['total_attended_s1']
        days_attended_s2=request.POST['days_attended_s2']
        total_attended_s2=request.POST['total_attended_s2']
        days_attended_s3=request.POST['days_attended_s3']
        total_attended_s3=request.POST['total_attended_s3']
        days_attended_s4=request.POST['days_attended_s4']
        total_attended_s4=request.POST['total_attended_s4']
        days_attended_s5=request.POST['days_attended_s5']
        total_attended_s5=request.POST['total_attended_s5']
        final1=(int(days_attended_s1)/int(total_attended_s1))*100
        final2=(int(days_attended_s2)/int(total_attended_s2))*100
        final3=(int(days_attended_s3)/int(total_attended_s3))*100
        final4=(int(days_attended_s4)/int(total_attended_s4))*100
        final5=(int(days_attended_s5)/int(total_attended_s5))*100
        Attendence.objects.create(student=Student.objects.get(staff=Staff.objects.get(id=student_id)),
                                  s1=final1,
                                  s2=final2,
                                  s3=final3,
                                  s4=final4,
                                  s5=final5)
        return render(request,'teacher_dashboard.html')
    return render(request,'attendence.html',{'list':list_of_student_id,'sub':department_choice})

def marks(request):
    list_of_student_id=[]
    list_of_staff=Staff.objects.all()
    for staff in list_of_staff:
        if not staff.is_teacher:
            list_of_student_id.append(staff.id)
    if request.POST:
        student_id=request.POST['student_id']
        marks_s1=request.POST['marks_s1']
        total_marks_s1=request.POST['total_marks_s1']
        marks_s2=request.POST['marks_s2']
        total_marks_s2=request.POST['total_marks_s2']
        marks_s3=request.POST['marks_s3']
        total_marks_s3=request.POST['total_marks_s3']
        marks_s4=request.POST['marks_s4']
        total_marks_s4=request.POST['total_marks_s4']
        marks_s5=request.POST['marks_s5']
        total_marks_s5=request.POST['total_marks_s5']
        final1=(int(marks_s1)/int(total_marks_s1))*100
        final2=(int(marks_s2)/int(total_marks_s2))*100
        final3=(int(marks_s3)/int(total_marks_s3))*100
        final4=(int(marks_s4)/int(total_marks_s4))*100
        final5=(int(marks_s5)/int(total_marks_s5))*100
        Marks.objects.create(student=Student.objects.get(staff=Staff.objects.get(id=student_id)),
                                  s1=final1,
                                  s2=final2,
                                  s3=final3,
                                  s4=final4,
                                  s5=final5)
        return render(request,'teacher_dashboard.html')
    return render(request,'marks.html',{'list':list_of_student_id,'sub':department_choice})






# Create your views here.
def teacher_login(request):
    logout(request)
    id = password = ''
    if request.POST:
        id = request.POST['id']
        password = request.POST['password']
        if id:
            user = authenticate(id=id, password=password)
            if user is not None:
                if user.is_active and user.is_teacher:
                    login(request, user)
                    return HttpResponseRedirect(f'teacher_dashboard/{id}/')
            else:
                return HttpResponse("INVALID PASSWORD")

    return render(request,'teacher_login.html')


def teacher_dashboard(request,id):
    return render(request,'teacher_dashboard.html')

teacher/templates/attendence.html
{% extends 'teacher_dashboard.html' %}
{% load static %}
{% block content %}

<form method="post" action={% url 'teacher:attend' %}>
  {% csrf_token  %}
  <div class="form-group col-md-6">
    <label for="select_student">Which Student</label>
      <select id="select_student" class="form-control" name="student_id">
        {% for s in list %}
        <option>{{s}}</option>
        {% endfor %}
      </select>
  </div>
  <div class="form-group">
    <label ></label>
    <input type="number" class="form-control" placeholder="Days Atended" name='days_attended_s1'>
    <input type="number" class="form-control" placeholder="Total Days" name='total_attended_s1'>
  </div>
  <div class="form-group">
    <label ></label>
    <input type="number" class="form-control" placeholder="Days Atended" name='days_attended_s2'>
    <input type="number" class="form-control" placeholder="Total Days" name='total_attended_s2'>
  </div>
  <div class="form-group">
    <label ></label>
    <input type="number" class="form-control" placeholder="Days Atended" name='days_attended_s3'>
    <input type="number" class="form-control" placeholder="Total Days" name='total_attended_s3'>
  </div>
  <div class="form-group">
    <label ></label>
    <input type="number" class="form-control" placeholder="Days Atended" name='days_attended_s4'>
    <input type="number" class="form-control" placeholder="Total Days" name='total_attended_s4'>
  </div>
  <div class="form-group">
    <label ></label>
    <input type="number" class="form-control" placeholder="Days Atended" name='days_attended_s5'>
    <input type="number" class="form-control" placeholder="Total Days" name='total_attended_s5'>
  </div>
  <div class="form-group">
  <input  type="submit" class="btn btn-active" value="Enter">
  </div>


</form>
{% endblock %}

teacher/templates/marks.html
4{% extends 'teacher_dashboard.html' %}
{% load static %}
{% block content %}

<form method="post" action={% url 'teacher:marks' %}>
  {% csrf_token  %}
  <div class="form-group col-md-6">
    <label for="select_student">Which Student</label>
      <select id="select_student" class="form-control" name="student_id">
        {% for s in list %}
        <option>{{s}}</option>
        {% endfor %}
      </select>
  </div>
  <div class="form-group">
    <label for="marks_s1">{{sub.0}}</label>
    <input type="number" class="form-control" placeholder="Marks Scored" name='marks_s1'>
    <input type="number" class="form-control" placeholder="Total Marks" name='total_marks_s1'>
  </div>
  <div class="form-group">
    <label for="marks_s2">{{sub.1}}</label>
    <input type="number" class="form-control" placeholder="Marks Scored" name='marks_s2'>
    <input type="number" class="form-control" placeholder="Total Marks" name='total_marks_s2'>
  </div>
  <div class="form-group">
    <label for="marks_s3" >{{sub.2}}</label>
    <input type="number" class="form-control" placeholder="Marks Scored" name='marks_s3'>
    <input type="number" class="form-control" placeholder="Total Marks" name='total_marks_s3'>
  </div>
  <div class="form-group">
    <label for="marks_s4">{{sub.3}}</label>
    <input type="number" class="form-control" placeholder="Marks Scored" name='marks_s4'>
    <input type="number" class="form-control" placeholder="Total Marks" name='total_marks_s4'>
  </div>
  <div class="form-group">
    <label for="marks_s5">{{sub.4}}</label>
    <input type="number" class="form-control" placeholder="Marks Scored" name='marks_s5'>
    <input type="number" class="form-control" placeholder="Total Marks" name='total_marks_s5'>
  </div>
  <div class="form-group">
  <input  type="submit" class="btn btn-active" value="Enter">
  </div>


</form>
{% endblock %}

teacher/templates/noticeform.html
{% extends 'teacher_dashboard.html' %}
{% load static %}
{% block content %}

<form class="mt-5"  action="{% url 'teacher:notice' %}" method="post">
    {% csrf_token %}
   <div class="form-group">
      <input type="text" name="notice"  class="form-control my-input" id="notice" placeholder="Whats the notice?">
   </div>

  <div class="form-group">
     <input type="submit"value="Send">
  </div>
</form>

{% endblock %}

teacher/templates/teacher_dashboard.html
{% extends 'home.html' %}
{% load static %}


{% block body %}
<center>
<div class="list-group">
  <a href="{% url 'teacher:notice' %}" class="list-group-item list-group-item-action">Add notice</a>
  <a href="{% url 'teacher:attend' %}" class="list-group-item list-group-item-action">Attendence</a>
  <a href="{% url 'teacher:marks' %}" class="list-group-item list-group-item-action">Enter Marks</a>
  <a href="#" class="list-group-item list-group-item-action">Porta ac consectetur ac</a>
  <a href="#" class="list-group-item list-group-item-action disabled" tabindex="-1" aria-disabled="true">Vestibulum at eros</a>
</div>
{% block content %}
{% endblock %}
  </center>
{% endblock %}

teacher/templates/teacher_login.html
{% extends 'home.html' %}
{% load static %}

{% block body %}
        <div class="row mt-5">
                <div class="col-md-4 mx-auto">

                      <form action="{% url 'teacher:teacher_login' %}" method="post" name="login">
                            {% csrf_token %}
                            <div class="text-center ">
                            <img src="{% static "teacher_2.png" %}" style=" border-radius:20%; width:100px;height:100px;" >
                                    <h2>Welcome Teachers</h2>
                                 </div>

                         <div class="form-group">
                            <input type="id" name="id"  class="form-control my-input" id="id" placeholder="Entr Your Id">
                         </div>
                         <div class="form-group">
                            <input type="password" name="password" id="password"  class="form-control my-input" placeholder="Password">
                         </div>

                         <div class="text-center ">

                            <button type="submit" class="btn btn-primary">Login</button>
                         </div>


                      </form>

                </div>
         </div>
{% endblock %}