miniproject/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',view=views.home,name='home'),
    path('student/',include('student.urls')),
    path('teacher/',include('teacher.urls')),
]

student/urls.py
from django.contrib import admin
from django.urls import path
from . import views
app_name='student'
urlpatterns = [

    path('student_login',view=views.student_login,name='student_login'),
    path('student_register',view=views.student_register,name='student_register'),
    path('student_info/<int:id>/',view=views.student_info,name='student_info'),
]

teacher/urls.py
from django.contrib import admin
from django.urls import path
from . import views
app_name='teacher'
urlpatterns = [

    path('teacher_login',view=views.teacher_login,name='teacher_login'),
    path('teacher_dashboard/<int:id>/',view=views.teacher_dashboard,name='teacher_dashboard'),
    path('teacher_dashboard/notice',view=views.notice,name='notice'),
    path('teacher_dashboard/attend',view=views.attend,name='attend'),
    path('teacher_dashboard/marks',view=views.marks,name='marks'),
]

templates/home.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <title>HOMEPAGE</title>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    </head>
        <body>

                <nav class="navbar navbar-dark bg-dark">
                    <a class="navbar-brand" href="#">University Portal</a>
                    
                </nav>

                <div class="container" style="margin: 5%">
                  {% block body %}
                    <div class="col">
                            <h1> Select one</h1>
                           <div class="row">
                        <div class="card mr-3" style="width: 18rem;">
                            <img src="{% static "student.png" %}" class="card-img-top" alt="...">
                            <div class="card-body">
                              <h5 class="card-title">Student</h5>
                              <p class="card-text">If you are student press below</p>
                              <a href="{% url 'student:student_login'%}" class="btn btn-primary">Press</a>
                            </div>
                          </div>

                          <div class="card" style="width: 18rem;">
                            <img src="{% static "teacher.png" %}" class="card-img-top" alt="...">
                            <div class="card-body">
                              <h5 class="card-title">Teacher</h5>
                              <p class="card-text">If you are teacher press below</p>
                              <a href="{% url 'teacher:teacher_login'%}" class="btn btn-primary">Press</a>
                            </div>
                          </div>
                        </div>
                    </div>
                    {% endblock %}
                </div>


















                <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
                <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
                <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
        </body>
</html>