miniproject/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',view=views.home,name='home'),
    path('student/',include('student.urls')),
    path('teacher/',include('teacher.urls')),
]

student/urls.py
from django.contrib import admin
from django.urls import path
from . import views
app_name='student'
urlpatterns = [

    path('student_login',view=views.student_login,name='student_login'),
    path('student_register',view=views.student_register,name='student_register'),
    path('student_info/<int:id>/',view=views.student_info,name='student_info'),
]

student/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser,BaseUserManager
section_choice=['CSE-NS']
year_choice=['Third Year']


class MyStaffManager(BaseUserManager):
    def create_user(self, id, password=None):
        """
        Creates and saves a User with the given email, date of
        birth and password.
        """
        if not id:
            raise ValueError('Users must have an id ')

        user = self.model(
            id=id,

        )

        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, id,  password):
        """
        Creates and saves a superuser with the given email, date of
        birth and password.
        """
        user = self.create_user(id,
            password=password,

        )
        user.is_admin = True
        user.save(using=self._db)
        return user


class Staff(AbstractBaseUser):
    id=models.IntegerField(unique=True,primary_key=True)
    password=models.CharField(max_length=100)
    is_teacher=models.BooleanField(default=False)
    is_admin =models.BooleanField(default=False)
    is_active=models.BooleanField(default=True)


    objects = MyStaffManager()

    USERNAME_FIELD = 'id'
    REQUIRED_FIELDS = []

    def get_full_name(self):
        # The user is identified by their email address
        return self.id

    def get_short_name(self):
        # The user is identified by their email address
        return self.id

    def __str__(self):              # __unicode__ on Python 2
        return str(self.id)

    def has_perm(self, perm, obj=None):
        "Does the user have a specific permission?"
        # Simplest possible answer: Yes, always
        return True

    def has_module_perms(self, app_label):
        "Does the user have permissions to view the app `app_label`?"
        # Simplest possible answer: Yes, always
        return True

    @property
    def is_staff(self):
        "Is the user a member of staff?"
        # Simplest possible answer: All admins are staff
        return self.is_admin














class Student(models.Model):
    staff=models.OneToOneField(Staff,on_delete=models.CASCADE,null=True,related_name='student_profile')
    stud_name=models.CharField(max_length=200)
    section=models.IntegerField(choices=((i,x) for i,x in enumerate(section_choice)),default=0)
    year = models.IntegerField(choices=((i,x) for i,x in enumerate(year_choice)),default=0)
    def __str__(self):
        return str(self.stud_name)
class Marks(models.Model):
    student=models.ForeignKey(Student,on_delete=models.CASCADE,related_name='mark_profile')
    s1=models.IntegerField(default=0)
    s2=models.IntegerField(default=0)
    s3=models.IntegerField(default=0)
    s4=models.IntegerField(default=0)
    s5=models.IntegerField(default=0)
class Attendence(models.Model):
    student=models.ForeignKey(Student,on_delete=models.CASCADE,related_name='attendence_profile')
    s1=models.IntegerField(default=0)
    s2=models.IntegerField(default=0)
    s3=models.IntegerField(default=0)
    s4=models.IntegerField(default=0)
    s5=models.IntegerField(default=0)

student/forms.py
from django import forms
from .models import Student

class StudentForm(forms.ModelForm):
    class Meta:
        model = Student
        fields = ('stud_name', 'section','year')





from django.contrib import admin
from django.contrib.auth.models import Group
from django.contrib.auth.admin import UserAdmin as BaseUserAdmin
from django.contrib.auth.forms import ReadOnlyPasswordHashField

from .models import Staff


class StaffForm(forms.ModelForm):
    """A form for creating new users. Includes all the required
    fields, plus a repeated password."""
    password1 = forms.CharField(label='Password', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Password confirmation', widget=forms.PasswordInput)

    class Meta:
        model = Staff
        fields = ('id',)

    def clean_password2(self):
        # Check that the two password entries match
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError("Passwords don't match")
        return password2

    def save(self, commit=True):
        # Save the provided password in hashed format
        user = super(StaffForm, self).save(commit=False)
        user.set_password(self.cleaned_data["password1"])
        if commit:
            user.save()
        return user


class StaffChangeForm(forms.ModelForm):
    """A form for updating users. Includes all the fields on
    the user, but replaces the password field with admin's
    password hash display field.
    """
    password = ReadOnlyPasswordHashField()

    class Meta:
        model = Staff
        fields = ('id', 'password', 'is_active', 'is_admin')

    def clean_password(self):
        # Regardless of what the user provides, return the initial value.
        # This is done here, rather than on the field, because the
        # field does not have access to the initial value
        return self.initial["password"]


class UserAdmin(BaseUserAdmin):
    # The forms to add and change user instances
    form = StaffChangeForm
    add_form = StaffForm

    # The fields to be used in displaying the User model.
    # These override the definitions on the base UserAdmin
    # that reference specific fields on auth.User.
    list_display = ('id', 'is_teacher', 'is_admin')
    list_filter = ('is_admin',)
    fieldsets = (
        (None, {'fields': ('id', 'password')}),
        ('Personal info', {'fields': ('is_teacher',)}),
        ('Permissions', {'fields': ('is_admin',)}),
    )
    # add_fieldsets is not a standard ModelAdmin attribute. UserAdmin
    # overrides get_fieldsets to use this attribute when creating a user.
    add_fieldsets = (
        (None, {
            'classes': ('wide',),
            'fields': ('id', 'is_teacher', 'password1', 'password2')}
        ),
    )
    search_fields = ('id',)
    ordering = ('id',)
    filter_horizontal = ()

# Now register the new UserAdmin...

# ... and, since we're not using Django's built-in permissions,
# unregister the Group model from admin.
admin.site.unregister(Group)

student/views.py
from django.shortcuts import render,redirect,render_to_response
from .forms import StudentForm,StaffForm
from .models import Staff,Student,Marks,Attendence
from teacher.models import Notice
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.template import RequestContext
from django.http import HttpResponseRedirect,HttpResponse
from teacher.models import department_choice

# Create your views here.
def student_login(request):
    logout(request)
    id = password = ''
    if request.POST:
        id = request.POST['rollnum']
        password = request.POST['password']
        if id:
            user = authenticate(id=id, password=password)
            if user is not None:
                if user.is_active:
                    login(request, user)
                    return HttpResponseRedirect(f'student_info/{id}/')
            else:
                return HttpResponse("INVALID PASSWORD")

    return render(request,'student_login.html')




def student_info(request,id):
    s=Staff.objects.get(pk=id)
    st=Student.objects.get(staff=s)
    listofnotice=Notice.objects.all()
    listofsub=department_choice
    m=a=None
    if Marks.objects.filter(student=st).exists():
        m=Marks.objects.filter(student=st).latest('s1')
        a=None
    if Attendence.objects.filter(student=st).exists():
        m=None
        a=Attendence.objects.filter(student=st).latest('s1')



    return render(request,'stud_info.html',{'m':m,'a':a,'notices':listofnotice,'sub':listofsub})


def student_register(request):
    student_form=StudentForm()
    staff_form=StaffForm()
    if request.method=='POST':


        student_form=StudentForm(request.POST)
        staff_form=StaffForm(request.POST)
        if staff_form.is_valid() and student_form.is_valid():
            newstaff=staff_form.save()
            newstudent=student_form.save(commit=False)
            newstudent.staff=newstaff
            newstudent.save()


            return HttpResponseRedirect('student_login')
    else:
        staff_form = StaffForm()
        student_form = StudentForm()



    context={
             'form':staff_form,'form2':student_form
    }
    return render(request,'student_register.html',context)

student/templates/stud_info.html
{% extends 'home.html' %}
{% block body %}
<center>
  {% if m %}
<h2>Result</h2>
  <table class="table">
  <thead class="thead-dark">
    <tr>
      <th scope="col">Sr no.</th>
      {% for s in sub %}

      <th scope="col">{{s}}</th>
      {% endfor %}
    </tr>
  </thead>
  <tbody>
    <tr>
      <th scope="row">1</th>
      <td>{{m.s1}}</td>
      <td>{{m.s2}}</td>
      <td>{{m.s3}}</td>
      <td>{{m.s4}}</td>
      <td>{{m.s5}}</td>
    </tr>
  </tbody>
</table>
{% endif %}
{% if a %}
<h2>Attendence</h2>
  <table class="table">
  <thead class="thead-dark">
    <tr>
      <th scope="col">Sr no.</th>
      {% for s in sub %}

      <th scope="col">{{s}}</th>
      {% endfor %}
    </tr>
  </thead>
  <tbody>
    <tr>
      <th scope="row">1</th>
      <td>{{a.s1}}</td>
      <td>{{a.s2}}</td>
      <td>{{a.s3}}</td>
      <td>{{a.s4}}</td>
      <td>{{a.s5}}</td>
    </tr>
  </tbody>
</table>
{% endif %}
<h2>Notice Board</h2>
  <table class="table">
  <thead class="thead-dark">
    <tr>
      <th scope="col">Notices</th>


    </tr>
  </thead>
  <tbody class="table-striped">
{% for n in notices %}
    <tr><td>{{n.notice}}</td></tr>
{% endfor %}
  </tbody>
</table>
</center>
{% endblock %}

student/templates/student_login.html
{% extends 'home.html' %}
{% load static %}

{% block body %}

        <div class="row mt-2">
                <div class="col-md-4 mx-auto">

                      <form action="{% url 'student:student_login' %}" method="post" name="login">
                        {% csrf_token %}
                            <div class="text-center ">
                                    <img src="{% static "student_2.png" %}" style=" border-radius:20%; width:100px;height:100px;" >
                                    <h2>Welcome Students</h2>
                                 </div>

                         <div class="form-group">
                           <label for="rollnum">Roll Number</label>
                            <input type="number" name="rollnum"  class="form-control my-input" id="rollnum" placeholder="Enter your roll number">
                         </div>
                         <div class="form-group">
                           <label for="password">Password</label>
                            <input type="password" name="password"  id="password"  class="form-control my-input" placeholder="Password">
                         </div>

                         <div class="text-center ">

                            <button type="submit" class="btn btn-primary">Login</button>
                         </div>
                         </form>
                         <form class="" action="{% url 'student:student_register' %}" method="post">
                           {% csrf_token %}

                           <div class="text-center mt-2">

                                  <button  class="btn btn-success">Signup</button>
                          </div>
                         </form>




                </div>
             </div>

{% endblock %}

student/templates/student_register.html
{% extends 'home.html' %}
{% load static %}

{% block body %}
        <div class="row mt-3">
                <div class="col-md-4 mx-auto">

                      <form method="post">
                        {% csrf_token %}
                            <div class="text-center ">
                              <img src="{% static "student_2.png" %}" style=" border-radius:20%; width:100px;height:100px;" >
                              <h2>Not yet regitered?</h2>
                                    {% for field in form %}
                                         <div class="form-group">
                                           <label for="{{field.if_for_label}}" class="Label" ><strong>{{field.html_name}}</strong></label>
                                            <p>{{field}}</p>
                                          </div>
                                    {% endfor %}
                                    {% for field in form2 %}
                                         <div class="form-group">
                                           <label for="{{field.if_for_label}}" class="Label" ><strong>{{field.html_name}}</strong></label>
                                            <p>{{field}}</p>
                                          </div>
                                    {% endfor %}
                              <button type="submit" class="btn btn-primary">Register</button>
                         </div>
                         </form>





                </div>
             </div>

{% endblock %}